name: Approve And Merge Dependabot PR

on:
  repository_dispatch:
    types:
      - approve-merge-dependabot-pr

jobs:
  approve-merge:
    name: Approve And Merge Dependabot PR
    runs-on: ubuntu-latest
    # Perform the auto approve action only when the PR is raised by dependabot
    steps:
      - name: Approve a Dependabot PR If Not Already Approved
        continue-on-error: true
        # Only if the check-approve-merge script return true (minor or patch versions and valid dependencies)
        if:  ${{ github.event.client_payload.auto-approve-merge == 'true' }}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ github.token }}
      - name: Merge a Dependabot PR
        continue-on-error: true
        # Only if the check-approve-merge script return true (minor or patch versions and valid dependencies)
        if:  ${{ github.event.client_payload.auto-approve-merge == 'true' }}
        # Auto merge the PR using dependabot command '@dependabot merge'
        run: gh pr comment --body "@dependabot merge" "$PR_URL"
        env:
          PR_URL: ${{ github.event.client_payload.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}
